import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { configured, supabase } from './lib/supabase';

const money = n => `¥${Number(n || 0).toFixed(2)}`;
const actionName = { restock: '补货', sale: '卖出', loss: '损耗', stocktake: '盘点' };
const emptyProduct = { name: '', category_id: '', cost_price: '', sale_price: '', quantity: 0, low_stock_threshold: 0, notes: '' };

function App() {
  const [session, setSession] = useState(undefined);
  useEffect(() => {
    if (!configured) { setSession(null); return; }
    supabase.auth.getSession().then(({ data }) => setSession(data.session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next));
    return () => listener.subscription.unsubscribe();
  }, []);
  if (session === undefined) return <div className="splash">正在打开小店管家…</div>;
  if (!configured) return <SetupNotice />;
  return <Routes><Route path="/login" element={session ? <Navigate to="/" replace /> : <Login />} /><Route path="/*" element={session ? <PrivateApp /> : <Navigate to="/login" replace />} /></Routes>;
}

function SetupNotice() { return <main className="setup"><div className="logo">小店管家</div><h1>还差一步配置</h1><p>请复制 <code>.env.example</code> 为 <code>.env.local</code>，并填入 Supabase 的项目地址和匿名密钥。</p><p>具体步骤在项目 <code>README.md</code> 中。配置完成后重启网站即可登录。</p></main>; }

function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [registering, setRegistering] = useState(false);
  async function submit(e) { e.preventDefault(); setMessage(''); const authEmail = email.includes('@') ? email.trim() : `${email.trim().toLowerCase()}@shop.local`; setBusy(true); if (registering) { const { error } = await supabase.auth.signUp({ email: authEmail, password }); setBusy(false); setMessage(error ? error.message : '账号已创建，可直接开始使用。'); return; } const { error } = await supabase.auth.signInWithPassword({ email: authEmail, password }); setBusy(false); if (error) setMessage('账号或密码不正确，请重试。'); }
  return <main className="login"><div className="login-card"><div className="logo">小店管家</div><p>{registering ? '首次使用：创建管理员账号' : '随时掌握库存和预计利润'}</p><form onSubmit={submit}><label>登录账号<input type="text" required value={email} onChange={e => setEmail(e.target.value)} placeholder="输入账号" /></label><label>密码<input type="password" required minLength="6" value={password} onChange={e => setPassword(e.target.value)} placeholder="至少 6 位" /></label>{message && <div className="error">{message}</div>}<button className="primary" disabled={busy}>{busy ? '处理中…' : registering ? '创建管理员账号' : '登录'}</button></form><button className="secondary full" onClick={() => { setRegistering(v => !v); setMessage(''); }}>{registering ? '已有账号，去登录' : '首次使用，创建管理员账号'}</button></div></main>;
}

function PrivateApp() { return <><div className="app-shell"><Routes><Route index element={<Dashboard />} /><Route path="products" element={<Products />} /><Route path="products/new" element={<ProductForm />} /><Route path="products/:id" element={<ProductDetail />} /><Route path="products/:id/edit" element={<ProductForm />} /><Route path="categories" element={<Categories />} /><Route path="me" element={<Me />} /><Route path="*" element={<NotFound />} /></Routes></div><Nav /></>; }
function Nav() { const { pathname } = useLocation(); const links = [['/','⌂','首页'],['/products','▤','商品'],['/categories','◫','分类'],['/me','◉','我的']]; const go = useNavigate(); return <nav className="bottom-nav">{links.map(([to, icon, label]) => <button key={to} className={pathname === to || (to !== '/' && pathname.startsWith(to)) ? 'active' : ''} onClick={() => go(to)}><span>{icon}</span>{label}</button>)}</nav>; }
function Header({ title, back = true, children }) { const go = useNavigate(); return <header className="page-header">{back ? <button className="back" onClick={() => window.history.length > 1 ? go(-1) : go('/')}>←</button> : <span className="back-space"/>}<h1>{title}</h1>{children || <button className="home" onClick={() => go('/')}>首页</button>}</header>; }

function useData() { const [state, setState] = useState({ loading: true, error: '', products: [], categories: [] }); const reload = async () => { setState(s => ({ ...s, loading: true, error: '' })); const [p, c] = await Promise.all([supabase.from('products').select('*, categories(name)').order('updated_at', { ascending: false }), supabase.from('categories').select('*').order('name')]); if (p.error || c.error) setState(s => ({ ...s, loading: false, error: `数据加载失败：${p.error?.message || c.error?.message || '请检查网络后重试。'}` })); else setState({ loading: false, error: '', products: p.data, categories: c.data }); }; useEffect(() => { reload(); }, []); return { ...state, reload }; }
function Loading({ error, retry }) { return <div className="state"><p>{error || '正在加载…'}</p>{error && <><button className="primary" onClick={retry}>重新加载</button><Link to="/">返回首页</Link></>}</div>; }

function Dashboard() { const { products, loading, error, reload } = useData(); if (loading || error) return <Loading error={error} retry={reload} />; const totals = products.reduce((a,p) => ({ qty:a.qty+Number(p.quantity), cost:a.cost+Number(p.cost_price)*p.quantity, sales:a.sales+Number(p.sale_price)*p.quantity }), {qty:0,cost:0,sales:0}); const low = products.filter(p => p.quantity <= p.low_stock_threshold); return <><Header title="小店管家" back={false}/><main><section className="welcome"><h2>今日库存概览</h2><p>库存金额会随商品和数量自动更新</p></section><section className="metrics"><Metric label="商品种类" value={`${products.length} 件`} /><Metric label="库存数量" value={`${totals.qty} 件`} /><Metric label="库存总成本" value={money(totals.cost)} /><Metric label="预计销售额" value={money(totals.sales)} /><Metric label="预计总利润" value={money(totals.sales-totals.cost)} important /><Metric label="低库存提醒" value={`${low.length} 件`} warn={low.length > 0}/></section>{low.length > 0 && <section className="panel"><h2>需要补货</h2>{low.map(p => <Link className="low-row" to={`/products/${p.id}`} key={p.id}><span>{p.name}</span><b>剩 {p.quantity} 件 / 预警 {p.low_stock_threshold}</b></Link>)}</section>}<section className="panel"><h2>最近更新</h2>{products.slice(0,5).map(p => <Link className="list-row" to={`/products/${p.id}`} key={p.id}><span><b>{p.name}</b><small>{p.categories?.name || '未分类'} · 库存 {p.quantity}</small></span><strong>{money((p.sale_price-p.cost_price)*p.quantity)}</strong></Link>)}{!products.length && <Empty text="还没有商品，先添加第一件货品吧。" link="/products/new" label="新增商品"/>}</section></main></> }
function Metric({ label, value, important, warn }) { return <div className={`metric ${important?'important':''} ${warn?'warn':''}`}><small>{label}</small><b>{value}</b></div>; }

function Products() { const { products, categories, loading, error, reload } = useData(); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); if (loading || error) return <Loading error={error} retry={reload}/>; const filtered = products.filter(p => p.name.includes(query.trim()) && (!category || p.category_id === category)); return <><Header title="商品"><Link className="text-btn" to="/products/new">+ 新增</Link></Header><main className="with-sticky"><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索商品名称"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分类</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><p className="count">共 {filtered.length} 件商品</p><section className="product-list">{filtered.map(p => <Link to={`/products/${p.id}`} className="product-card" key={p.id}><div><h2>{p.name}</h2><p>{p.categories?.name || '未分类'} · 售价 {money(p.sale_price)}</p></div><div className={p.quantity <= p.low_stock_threshold ? 'stock low' : 'stock'}>库存 <b>{p.quantity}</b>{p.quantity <= p.low_stock_threshold && <small>低库存</small>}</div></Link>)}{!filtered.length && <Empty text="没有找到商品。" link="/products/new" label="新增商品"/>}</section></main></>; }

function ProductForm() { const { id } = useParams(); const go = useNavigate(); const [categories,setCategories]=useState([]); const [form,setForm]=useState(emptyProduct); const [loading,setLoading]=useState(Boolean(id)); const [message,setMessage]=useState(''); useEffect(()=>{(async()=>{const c=await supabase.from('categories').select('*').order('name'); setCategories(c.data||[]); if(id){const {data,error}=await supabase.from('products').select('*').eq('id',id).single(); if(error) setMessage('商品不存在或加载失败。'); else setForm({...data, category_id:data.category_id||''});}setLoading(false);})()},[id]); const set=(key,val)=>setForm(f=>({...f,[key]:val})); async function save(e){e.preventDefault();setMessage('');const data={...form,category_id:form.category_id||null,cost_price:Number(form.cost_price),sale_price:Number(form.sale_price),quantity:Number(form.quantity),low_stock_threshold:Number(form.low_stock_threshold)};const result=id?await supabase.from('products').update({...data,updated_at:new Date().toISOString()}).eq('id',id):await supabase.from('products').insert(data);if(result.error)setMessage(result.error.message);else go('/products',{replace:true});} if(loading)return <Loading/>; return <><Header title={id?'编辑商品':'新增商品'}/><main><form className="form panel" onSubmit={save}><label>商品名称<input required maxLength="80" value={form.name} onChange={e=>set('name',e.target.value)} placeholder="如：农夫山泉 550ml"/></label><label>商品分类<select value={form.category_id} onChange={e=>set('category_id',e.target.value)}><option value="">未分类</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="two"><label>进价（元）<input required min="0" step="0.01" type="number" inputMode="decimal" value={form.cost_price} onChange={e=>set('cost_price',e.target.value)}/></label><label>售价（元）<input required min="0" step="0.01" type="number" inputMode="decimal" value={form.sale_price} onChange={e=>set('sale_price',e.target.value)}/></label></div><div className="two"><label>当前库存<input required min="0" type="number" inputMode="numeric" value={form.quantity} onChange={e=>set('quantity',e.target.value)}/></label><label>低库存预警<input required min="0" type="number" inputMode="numeric" value={form.low_stock_threshold} onChange={e=>set('low_stock_threshold',e.target.value)}/></label></div><label>备注<textarea maxLength="300" value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="可记录规格、摆放位置等"/></label>{message&&<div className="error">{message}</div>}<button className="primary">保存商品</button></form></main></>; }

function ProductDetail(){const {id}=useParams();const go=useNavigate();const [p,setP]=useState(null);const [records,setRecords]=useState([]);const [error,setError]=useState('');const [adjust,setAdjust]=useState(false);const reload=async()=>{const [product,history]=await Promise.all([supabase.from('products').select('*, categories(name)').eq('id',id).single(),supabase.from('inventory_records').select('*').eq('product_id',id).order('created_at',{ascending:false}).limit(10)]);if(product.error)setError('商品不存在或加载失败。');else{setP(product.data);setRecords(history.data||[]);}};useEffect(()=>{reload()},[id]);async function remove(){if(!confirm(`确定删除“${p.name}”吗？这会同时删除它的库存记录。`))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error)setError(error.message);else go('/products',{replace:true});}if(error)return <><Header title="商品详情"/><Loading error={error} retry={reload}/></>;if(!p)return <Loading/>;const cost=p.cost_price*p.quantity,sales=p.sale_price*p.quantity;return <><Header title="商品详情"><button className="text-btn" onClick={()=>go(`/products/${id}/edit`)}>编辑</button></Header><main><section className="detail-title"><h2>{p.name}</h2><p>{p.categories?.name||'未分类'} {p.quantity<=p.low_stock_threshold&&<span className="badge">低库存</span>}</p></section><section className="metrics details"><Metric label="当前库存" value={`${p.quantity} 件`}/><Metric label="单件预计利润" value={money(p.sale_price-p.cost_price)}/><Metric label="库存总成本" value={money(cost)}/><Metric label="库存预计利润" value={money(sales-cost)} important/></section><section className="panel"><h2>库存操作</h2><button className="primary" onClick={()=>setAdjust(true)}>调整库存</button><p className="muted">补货、卖出、损耗、盘点都会留下记录。</p></section><section className="panel"><h2>商品信息</h2><div className="info"><span>进价</span><b>{money(p.cost_price)}</b><span>售价</span><b>{money(p.sale_price)}</b><span>低库存预警</span><b>{p.low_stock_threshold} 件</b>{p.notes&&<><span>备注</span><b>{p.notes}</b></>}</div></section><section className="panel"><h2>最近库存记录</h2>{records.length?records.map(r=><div className="record" key={r.id}><span><b>{actionName[r.action]}</b><small>{new Date(r.created_at).toLocaleString('zh-CN')}</small>{r.notes&&<small>{r.notes}</small>}</span><strong className={r.quantity_change>=0?'up':'down'}>{r.quantity_change>=0?'+':''}{r.quantity_change} 件</strong></div>):<p className="muted">还没有调整记录。</p>}</section><button className="danger" onClick={remove}>删除商品</button></main>{adjust&&<AdjustModal product={p} close={()=>setAdjust(false)} done={()=>{setAdjust(false);reload()}}/>}</>}
function AdjustModal({product,close,done}){const [action,setAction]=useState('restock');const [value,setValue]=useState('');const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();const val=Number(value);if(!Number.isInteger(val)||val<0){setError('请输入大于等于 0 的整数。');return}if(['sale','loss'].includes(action)&&val>product.quantity){setError('数量不能超过当前库存。');return}setBusy(true);const {error}=await supabase.rpc('adjust_inventory',{p_product_id:product.id,p_action:action,p_value:val,p_notes:notes});setBusy(false);if(error)setError(error.message);else done()}return <div className="overlay"><form className="modal" onSubmit={submit}><h2>调整库存</h2><label>操作类型<select value={action} onChange={e=>setAction(e.target.value)}>{Object.entries(actionName).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>{action==='stocktake'?'盘点后的实际库存':'数量'}<input required type="number" inputMode="numeric" min="0" value={value} onChange={e=>setValue(e.target.value)} placeholder={action==='stocktake'?`当前为 ${product.quantity}`:'输入数量'}/></label><label>备注（可选）<input maxLength="200" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="例如：供货商送货"/></label>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" onClick={close}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'确认调整'}</button></div></form></div>}

function Categories(){const {categories,products,loading,error,reload}=useData();const [name,setName]=useState('');const [message,setMessage]=useState('');async function add(e){e.preventDefault();const {error}=await supabase.from('categories').insert({name:name.trim()});if(error)setMessage('分类名称重复或保存失败。');else{setName('');setMessage('');reload()}}async function edit(c){const n=prompt('修改分类名称',c.name);if(!n?.trim()||n.trim()===c.name)return;const {error}=await supabase.from('categories').update({name:n.trim()}).eq('id',c.id);if(error)setMessage('修改失败，分类名称可能重复。');else reload()}async function del(c){const used=products.some(p=>p.category_id===c.id);if(used){setMessage(`“${c.name}”下仍有商品，请先修改商品分类。`);return}if(confirm(`确定删除分类“${c.name}”吗？`)){const {error}=await supabase.from('categories').delete().eq('id',c.id);if(error)setMessage(error.message);else reload()}}if(loading||error)return <Loading error={error} retry={reload}/>;return <><Header title="商品分类"/><main><form className="inline-form panel" onSubmit={add}><input required maxLength="40" value={name} onChange={e=>setName(e.target.value)} placeholder="输入分类名称，如：饮料"/><button className="primary">新增</button></form>{message&&<div className="error">{message}</div>}<section className="panel">{categories.length?categories.map(c=><div className="category-row" key={c.id}><span><b>{c.name}</b><small>{products.filter(p=>p.category_id===c.id).length} 件商品</small></span><div><button onClick={()=>edit(c)}>改名</button><button className="delete-mini" onClick={()=>del(c)}>删除</button></div></div>):<p className="muted">还没有分类。可先建立“饮料”“零食”等分类。</p>}</section></main></>}
function Me(){const go=useNavigate();const [busy,setBusy]=useState(false);async function exportCsv(){const {data,error}=await supabase.from('products').select('*,categories(name)').order('name');if(error)return alert('导出失败，请重试。');const head=['商品名称','分类','进价','售价','当前库存','低库存预警','备注'];const rows=data.map(p=>[p.name,p.categories?.name||'',p.cost_price,p.sale_price,p.quantity,p.low_stock_threshold,p.notes].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','));const blob=new Blob(['\ufeff'+[head.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`小店库存_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}async function logout(){setBusy(true);await supabase.auth.signOut();go('/login')}return <><Header title="我的"/><main><section className="panel"><h2>数据备份</h2><p className="muted">导出当前商品和库存清单，可在 Excel 中打开。</p><button className="secondary" onClick={exportCsv}>导出 CSV 清单</button></section><section className="panel"><h2>账户</h2><p className="muted">当前为老板账号。商品数据只对本账号可见。</p><button className="danger" onClick={logout} disabled={busy}>{busy?'退出中…':'退出登录'}</button></section></main></>}
function Empty({text,link,label}){return <div className="empty"><p>{text}</p>{link&&<Link className="primary link-button" to={link}>{label}</Link>}</div>};function NotFound(){return <main><Header title="页面不存在"/><div className="state"><p>这个页面可能已被移动。</p><Link className="primary link-button" to="/">返回首页</Link></div></main>};
export default App;
